/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author 2 info
 */
public class Questao1 extends javax.swing.JFrame {

    /**
     * Creates new form Questao1
     */
    public Questao1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Errada1 = new javax.swing.JLabel();
        Errada2 = new javax.swing.JLabel();
        Certa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 430, 90, 20);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 420, 90, 40);

        Errada1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Errada1MouseClicked(evt);
            }
        });
        getContentPane().add(Errada1);
        Errada1.setBounds(100, 340, 110, 40);

        Errada2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Errada2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Errada2MouseEntered(evt);
            }
        });
        getContentPane().add(Errada2);
        Errada2.setBounds(320, 340, 110, 40);

        Certa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CertaMouseClicked(evt);
            }
        });
        getContentPane().add(Certa);
        Certa.setBounds(210, 340, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/6.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -40, 500, 570);

        setSize(new java.awt.Dimension(515, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new TelaPrinc().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new Inicial().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void Errada1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Errada1MouseClicked
        JOptionPane.showMessageDialog(null, "Resposta Incorreta!");
    }//GEN-LAST:event_Errada1MouseClicked

    private void Errada2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Errada2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Errada2MouseEntered

    private void Errada2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Errada2MouseClicked
        JOptionPane.showMessageDialog(null, "Resposta Incorreta!");
    }//GEN-LAST:event_Errada2MouseClicked

    private void CertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CertaMouseClicked
       JOptionPane.showMessageDialog(null, "Certa Resposta!");
    }//GEN-LAST:event_CertaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questao1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questao1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questao1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questao1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questao1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Certa;
    private javax.swing.JLabel Errada1;
    private javax.swing.JLabel Errada2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
